version: '3.7'
services:
  vju-ts-boilerplate:
    build: .
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
    ports:
      - '5000:5000'
